#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    linef1,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl9,  statusLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, sonar1,         sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           emotor1,       tmotorVex269_MC29, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int sonarCheck = 0;
int lineCount = 0;
bool turn1Done = false;
bool turn2Done = false;

void goForward();
void wallDetect();
void leftTurn();
void rightTurn();
void turn1Cleanup();
void turn2Cleanup();

task main()
{
turnLEDOff(statusLED);
getMotorEncoder(emotor1);


bool buttonStop = false;
  while(1==1)
{
	//start the robot forward upon the button press
	 if (SensorValue(startButton) == 1 && buttonStop == false)
	{
		goForward();
	}

	//scan the environment to see if 1st barrier is observed
	if (SensorValue(sonar1) <= 90 && SensorValue(sonar1) >= 5 && turn1Done == false)
	{
			//wall detected
			wallDetect();

			//check to see if sonar has confirmed wall at least 35 times
			if (sonarCheck >= 35)
			{
				//initiate 1st left turn
				//start tracking motor encoder during turn
				while(getMotorEncoder(emotor1) <= 400 && turn1Done == false)
					{
						leftTurn();
					}
					//turn 1 is complete
					turn1Cleanup();
			}

	}

	//scan the environment to see if 2nd barrier is observed
	if (SensorValue(sonar1) <= 120 && SensorValue(sonar1) >= 1 && turn1Done == true && turn2Done == false)
		{
			wallDetect();

			if (sonarCheck >= 35)
			{
				//start motor encoder for right turn
				while(abs(getMotorEncoder(emotor1)) <= 305)
					{
						rightTurn();
					}
					//turn 2 is complete, stop motor
					turn2Cleanup();
			}
	  }
	if (turn1Done == true && turn2Done == true)
		{
			turnLEDOn(statusLED);
			if (SensorValue(linef1)>= 3000)
			{
				lineCount++;
				wait(.25);
					if (lineCount >= 1)
					{
							wait(0.5);
					  	stopMotor(motor1);
					  	stopMotor(motor2);
					}
			}
		}
 }
}


void goForward()
{
	resetMotorEncoder(emotor1);
	startMotor(motor1, 55);
	startMotor(motor2, 55);
}

void wallDetect()
{
	sonarCheck++;
	waitInMilliseconds(20);
}

void leftTurn()
{
	startMotor(emotor1, 127);
}

void rightTurn()
{
	startMotor(emotor1, -127);
}

void turn1Cleanup()
{
	stopMotor(emotor1);
	resetMotorEncoder(emotor1);
	sonarCheck = 0;
	turn1Done = true;
}

void turn2Cleanup()
{
	stopMotor(emotor1);
	resetMotorEncoder(emotor1);
	sonarCheck = 0;
	turn2Done = true;
	wait(2);
}
